- app/controllers/catalog_controller.rb
- app/models/blacklight_config.rb
- app/values/show_field.rb
- spec/controllers/catalog_controller_spec.rb
- spec/models/blacklight_config_spec.rb
- spec/support/view_partial_doubles_disable.rb
- spec/values/show_field_spec.rb
- spec/views/catalog/_show_default.html.erb_spec.rb
> Show all fields in show view.

- spec/models/files/yml_file_spec.rb
This is a temporary fix - filing a ticket to figure out the right approach (or at least discuss it)
> Use GenericAsset as DummyAsset's parent

- config/newrelic.yml
Gets rid of an annoying new relic error.
> Fixed newrelic.yml entry.

- app/models/triple_powered_resource.rb
- app/repositories/fedora_ldp_repository.rb
- lib/oregon_digital/graph_mutators/subject_changer.rb
- lib/oregon_digital/models/metadata.rb
- spec/lib/oregon_digital/graph_mutators/subject_changer_spec.rb
- spec/models/generic_asset_spec.rb
- spec/models/triple_powered_resource_spec.rb
This is temporary until we can get something like Marmotta set up.
> Store Deep RDF in Fedora

- Gemfile
- Gemfile.lock
- app/controllers/admin_controller.rb
- app/controllers/application_controller.rb
- app/models/ability.rb
- app/models/user.rb
- app/views/_user_util_links.html.erb
- app/views/admin/index.html.erb
- circle.yml
- config/routes.rb
- db/migrate/20150429165654_user_roles.rb
- db/schema.rb
- spec/controllers/admin_controller_spec.rb
- spec/controllers/roles_controller_spec.rb
- spec/factories/roles.rb
- spec/factories/users.rb
- spec/features/hydra_editor_spec.rb
- spec/models/ability_spec.rb
- spec/support/capybara-screenshot.rb
- spec/views/_user_util_links.html.erb_spec.rb
- spec/views/admin/index.html.erb_spec.rb
> adds role management for admin permissions

- Gemfile.lock
My fault, sorry, I should go home early and reflect on what I've done
> Fix bad revision issue

- .gitignore
- Gemfile
- Gemfile.lock
- Rakefile
- app/models/triple_powered_resource.rb
- app/repositories/marmotta_connection.rb
- app/repositories/marmotta_repository.rb
- app/repositories/marmotta_resource.rb
- config/initializers/rails_config.rb
- config/settings.yml
- lib/oregon_digital.rb
- spec/models/triple_powered_resource_spec.rb
- spec/repositories/marmotta_connection_spec.rb
- spec/repositories/marmotta_resource_spec.rb
This makes resources use LDCache to automatically fetch labels and other metadata on access. It also uses Marmotta as the backend caching triple store instead of Fedora.
> Marmotta Repository

- Rakefile
- app/composites/composite_label.rb
- app/models/triple_powered_resource.rb
- app/repositories/marmotta_connection.rb
- app/repositories/marmotta_resource.rb
- app/repositories/sparql_with_context.rb
- app/services/all_label_finder.rb
- app/services/language_selector.rb
- circle.yml
- config/jetty.yml
- spec/composites/composite_label_spec.rb
- spec/models/triple_powered_resource_spec.rb
- spec/services/language_selector_spec.rb
This finds all english labels and selects the first one, if possible. Useful for
indexing.
> Add preferred label discovery.

- app/models/blacklight_config/show_configuration.rb
- app/views/catalog/_edit_action.html.erb
- config/application.rb
- spec/models/ability_spec.rb
- spec/models/blacklight_config_spec.rb
- spec/views/catalog/_edit_action.html.erb_spec.rb
> adds edit button in show view for admin

- app/composites/composite_enhancement_factory.rb
- app/enhancements/label_enhancement.rb
- app/models/enriched_solr_document.rb
- spec/enhancements/label_enhancement_spec.rb
This helps smooth over the interface difference between the composite
enhancement and a regular enhancement as well.
> Allow an enhancement to return multiple properties.

- spec/views/catalog/_show_default.html.erb_spec.rb
Closes #133 Already configured. Extended tests to show empty fields don't get displayed and all other filled out fields get dispalyed.
> Adds tests to show all fields that are filled out, show up

- app/controllers/sets_controller.rb
- app/indexing_services/identifiable_indexing.rb
- app/indexing_services/indexing_service.rb
- app/models/generic_asset.rb
- app/models/search_builder.rb
- app/values/maybe_identifiable.rb
- app/views/sets/_home_text.html.erb
- config/locales/en.yml
- config/routes.rb
- spec/controllers/sets_controller_spec.rb
- spec/models/generic_asset_spec.rb
- spec/models/search_builder_spec.rb
- spec/views/sets/_home_text.html.erb_spec.rb
This creates landing pages for GenericSets. Search result links currently don't point to links in the set context, but that's an issue for #147
Closes #38
> Collection landing pages

- app/models/blacklight_config/show_actions.rb
- spec/models/blacklight_config_spec.rb
> Allow editing from the search results.

- app/values/derivative_path.rb
- lib/oregon_digital/derivative_injector.rb
- lib/oregon_digital/derivatives/derivative_callback.rb
- lib/oregon_digital/file_distributor.rb
- spec/lib/oregon_digital/derivative_injector_spec.rb
- spec/lib/oregon_digital/derivatives/processors/pdf_processor_spec.rb
- spec/lib/oregon_digital/file_distributor_spec.rb
- spec/values/derivative_path_spec.rb
This adds an easy way to get the relative path of a derivative path.
> Derivative Path Object

- .gitignore
- Capfile
- Gemfile
- Gemfile.lock
- config/database.yml
- config/deploy.rb
- config/deploy/staging.rb
- config/environments/staging.rb
- config/fedora.yml
- config/jetty.yml
- config/secrets.yml
- config/settings/staging.yml
- config/solr.yml
Allows for OD2 to be deployed to staging.
> Add deploy configs

- spec/rails_helper.rb
- spec/support/fedora_cleaner.rb
Fixes my tests - no idea why I'm the only one with issues though
> Always use webmock localhost exception

- Gemfile
- Gemfile.lock
- app/assets/javascripts/blacklight_gallery.js
- app/assets/stylesheets/blacklight_gallery.css.scss
- app/models/blacklight_config.rb
- app/models/blacklight_config/gallery.rb
- app/values/solr_document_derivative_paths.rb
- app/views/catalog/_index_slideshow.html.erb
- app/views/catalog/_show_image.html.erb
- spec/models/solr_document_spec.rb
This implements all of blacklight gallery. Likely we'll want to handle this on a
per-set basis, and probably only parts of it.
Closes #139
> Implement Blacklight-Gallery

- app/enhancements/label_enhancement.rb
- app/models/solr_document.rb
- app/values/enriched_solr_property_result.rb
- app/values/singular_solr_property.rb
- app/values/solr_property.rb
- spec/models/solr_document_spec.rb
- spec/values/enriched_solr_property_result_spec.rb
- spec/values/solr_property_spec.rb
This should make things work wherever a solr document is used.
> Show preferred labels.

- app/jobs/create_derivatives_job.rb
- lib/oregon_digital/derivative_injector.rb
- lib/oregon_digital/derivatives/delayed_runner.rb
- spec/features/hydra_editor_spec.rb
- spec/integrations/derivatives/document_derivatives_spec.rb
- spec/integrations/derivatives/image_derivatives_spec.rb
- spec/jobs/create_derivatives_job_spec.rb
- spec/lib/oregon_digital/derivative_injector_spec.rb
- spec/lib/oregon_digital/derivatives/runner_finder_spec.rb
- spec/oregon_digital/derivatives/delayed_runner_spec.rb
- spec/support/active_job.rb
> Move derivative generation into ActiveJob.

- app/forms/generic_asset_form.rb
- app/views/records/_form.html.erb
- spec/views/records/_form.html.erb_spec.rb
> Warn user when ingesting and content is present

- app/enhancements/label_enhancement.rb
- app/models/blacklight_config/search_field.rb
- app/values/enriched_solr_property_result.rb
- app/values/solr_property.rb
- spec/models/blacklight_config/search_field_spec.rb
- spec/values/enriched_solr_property_result_spec.rb
- spec/values/solr_property_spec.rb
> Search Enriched Properties

- Gemfile
- Gemfile.lock
- app/assets/javascripts/application.js
- app/assets/javascripts/enable_best_in_place.js
- app/controllers/admin/facets_controller.rb
- app/facades/facet_configuration_facade.rb
- app/models/blacklight_config/facet_fields.rb
- app/models/facet_field.rb
- app/views/admin/facets/_field.html.erb
- config/locales/en.yml
- db/migrate/20150723222437_add_label_to_facet_fields.rb
- db/schema.rb
- spec/controllers/admin/facets_controller_spec.rb
- spec/models/blacklight_config_spec.rb
- spec/models/facet_field_spec.rb
> Edit labels for facets

- Gemfile
- Gemfile.lock
- app/assets/javascripts/blacklight_oembed.js
- app/controllers/records_controller.rb
- app/forms/external_asset_form.rb
- app/forms/generic_asset_form.rb
- app/models/blacklight_config.rb
- app/models/blacklight_config/embed.rb
- app/models/external_asset.rb
- app/models/od_data_model.rb
- app/models/solr_document.rb
- app/values/cleaned_attributes.rb
- config/initializers/hydra_editor.rb
- config/initializers/oembed_providers.rb
- config/locales/en.yml
- config/routes.rb
- spec/features/hydra_editor_spec.rb
- spec/forms/external_asset_form_spec.rb
- spec/forms/generic_asset_form_spec.rb
- spec/models/blacklight_config_spec.rb
- spec/models/od_data_model_spec.rb
- spec/models/solr_document_spec.rb
This enables external resources via O-Embed endpoints. Currently configured for everything that comes with Ruby-OEmbed as well as OSU's mediaspace.
Closes #114
> External Resource Support

- db/schema.rb
Makes schema.rb match what you get on a clean `rake db:migrate` run
> Fix schema

- Gemfile.lock
- app/models/generic_asset.rb
- config/initializers/noid.rb
- spec/models/generic_asset_spec.rb
> Revert to active_fedora-noid 0.3.0

- app/decorators/has_content.rb
- spec/features/hydra_editor_spec.rb
> Add mime type when uploading content.

- app/controllers/catalog_controller.rb
- spec/controllers/catalog_controller_spec.rb
> Add access control enforcement for Item Record.

- Gemfile
- Gemfile.lock
- config/application.rb
- config/environments/development.rb
- config/routes.rb
> adds sidekiq

- app/assets/stylesheets/main.scss
- app/controllers/reviewer_controller.rb
- app/models/blacklight_config/show_actions.rb
- app/models/solr_document.rb
- app/views/catalog/_reviewer_action.html.erb
- config/routes.rb
- spec/controllers/reviewer_controller_spec.rb
- spec/models/blacklight_config_spec.rb
- spec/views/catalog/_reviewer_action.html.erb_spec.rb
> added review link in record item page

- app/controllers/admin/form_templates_controller.rb
- app/models/form_template.rb
- spec/models/form_template_spec.rb
> Prevent hidden template properties from persisting

- app/assets/javascripts/toggle_hidden.js.coffee
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/ingest.scss
- app/forms/generic_asset_form.rb
- app/views/records/_form.html.erb
- spec/features/hydra_editor_spec.rb
- spec/forms/generic_asset_form_spec.rb
- spec/views/records/_form.html.erb_spec.rb
> Hide fields not in template

- app/models/blacklight_config/search_field_configuration.rb
- spec/models/blacklight_config_spec.rb
Swaps full text with all fields.
> Make all fields default

- app/controllers/catalog_controller.rb
- app/values/record_id.rb
- spec/controllers/catalog_controller_spec.rb
- spec/values/record_id_spec.rb
> redirects from old URL to new URL

- circle.yml
Fixes libreoffice errors in Circle.
> Fix Circle config for broken ubuntu repo.

- README.md
> Fixes coveralls badge
